name: Continuos Integration
on: 
    push: 
        branches: ["develop"]
    pull_request:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'
            - name: Install dependencies
              run: npm install
            - name: Up Database
              run: docker-compose up -d db-postgres
              env:
                DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
                DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
                DATABASE_DB: ${{ secrets.DATABASE_DB }}
                DATABASE_USER: ${{ secrets.DATABASE_USER }}
                DATABASE_PASS: ${{ secrets.DATABASE_PASS }}
            - name: Build
              run: npm run build
            - name: Deploy
              run: echo "Deploying to production"
    